finchcollector/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
 # Add the include function to the import
from django.urls import path, include
	
urlpatterns = [
     path('admin/', admin.site.urls),
     # '' represents the "starts with" path
     path('', include('main_app.urls')),
 ]

main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('items/', views.items_index, name='index'),
    path('items/<int:item_id>/', views.items_detail, name='item'),
    path('items/create/', views.ItemCreate.as_view(), name='item_create'),
    path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='item_update'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='item_delete'),
    path('cats/<int:item_id>/add_request/', views.add_request, name='add_request'),
    path('players/<int:item_id>/assoc_player/<int:player_id>/', views.assoc_player, name='assoc_player'),
    path('players/', views.PlayerList.as_view(), name = 'players_index'),
    path('players/<int:pk>/', views.PlayerDetail.as_view(), name = 'players_detail'),
    path('players/create/', views.PlayerCreate.as_view(), name = 'players_create'),
    path('players/<int:pk>/update/', views.PlayerUpdate.as_view(), name = 'players_update'),
    path('players/<int:pk>/delete/', views.PlayerDelete.as_view(), name = 'players_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
TRADE = (
    ('F', 'Free'),
    ('I', 'Items'),
    ('M', 'Money')
)

# Create your models here.
class Player(models.Model):
    name = models.CharField(max_length=50)
    level = models.IntegerField(max_length=50)
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("players_detail", kwargs={"pk": self.pk})

class Item(models.Model):
    name = models.CharField(max_length=100)
    quality = models.CharField(max_length=100)
    effect = models.TextField(max_length=250)
    amount = models.IntegerField()
    players = models.ManyToManyField(Player)
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("item", kwargs={"item_id": self.id})
    
class Request(models.Model):
    date = models.DateField('Trade Request Date')
    trade = models.CharField(
        max_length=1,
        choices=TRADE,
        default=TRADE[0][0])
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_trade_display()} on {self.date}"
    class Meta:
        ordering = ['-date']


    
    
   
    

main_app/forms.py
from django.forms import ModelForm
from .models import Request

class RequestForm(ModelForm):
  class Meta:
    model = Request
    fields = ['date', 'trade']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import *
from django.views.generic import *
from .models import Item, Player
from .forms import RequestForm

# Define the home view
def home(request):
  # Include an .html file extension - unlike when rendering EJS templates
  return render(request, 'home.html')
def about(request):
    return render(request, 'about.html') 
def items_index(request):
  items = Item.objects.all()
  # We pass data to a template very much like we did in Express!
  return render(request, 'items/index.html', {
    'items': items
  })
def items_detail(request, item_id):
    item = Item.objects.get(id=item_id)
    id_list = item.players.all().values_list('id')
    unassigned_players = Player.objects.exclude(id__in=id_list)
    request_form = RequestForm()
    return render(request, 'items/details.html', { 'item' : item, 'request_form': request_form, 'players': unassigned_players})
def add_request(request, item_id):
    form = RequestForm(request.POST)
    if form.is_valid():
        new_request = form.save(commit=False)
        new_request.item_id = item_id
        new_request.save()
    return redirect('item', item_id=item_id)
def assoc_player(request, player_id, item_id):
    Item.objects.get(id=item_id).players.add(player_id)
    return redirect('item', item_id=item_id)
class ItemCreate(CreateView):
    model = Item
    fields = '__all__'
    success_url = '/items'
class ItemUpdate(UpdateView):
    model = Item
    fields = '__all__'
class ItemDelete(DeleteView):
    model = Item
    success_url = '/items'
class PlayerList(ListView):
    model = Player
class PlayerDetail(DetailView):
    model = Player
class PlayerCreate(CreateView):
    model = Player
    fields = '__all__'    
class PlayerUpdate(UpdateView):
    model = Player
    fields = '__all__'
class PlayerDelete(DeleteView):
    model = Player
    success_url = '/players'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the TF2 Item Collector</h1>
<hr>
<p>Check out your items, and impress your friends... and enemies!</p>
<footer>All Rights Reserved, &copy; 2022 TF2 Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cat Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home'%}" class="left brand-logo">&nbsp;&nbsp;TF2 Item Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about'%}">About</a></li>
          <li><a href="{% url 'index'%}">View Items</a></li>
          <li><a href="{% url 'item_create' %}">Add Items</a></li>
        </ul>
      </div>
      
    </nav>
  </header>
  <main class="container">  
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 James Kokol &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/items/details.html
{% extends 'base.html' %}
{% block content %}

<h1>Item Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ item.name }}</span>
        <p>Breed: {{ item.quality }}</p>
        <p>Description: {{ item.amount }}</p>
        {% if item.effect == 'None' %}
          <p>No Effect</p>
        {% else %}
          <p>{{ item.effect }}</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'item_update' item.id %}">Edit</a>
        <a href="{% url 'item_delete' item.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <form action="{% url 'add_request' item.id %}" method="POST">
        {% csrf_token %}
        {{ request_form.as_p}}
        <input type='submit' class="btn" value="Make Trade Request">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Trade Type</th></tr>
      </thead>
      <tbody>
        {% for request in item.request_set.all %}
          <tr>
            <td>{{request.date}}</td>
            <td>{{request.get_trade_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>
<!-- This is all new markup to be added just above the <script> tag -->
<hr>
<div class="row">
      <div class="">
        <h3>Users who have a {{ item.quality }} {{ item.name }}</h3>
        {% if item.players.count %}
          {% for player in item.players.all %}
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                  Player: {{player.name}} || Level: {{player.level}}
                </span>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h5>No One! Be the First!</h5>
        {% endif %}
      </div>
      <!-- Available toys will come after this line -->
      <h3>Claim Item</h3>
      {% if players.count %}
        {% for player in players.all %}
        <div class="card">
            <div class="card-content">
              <span class="card-title">
                Player: {{player.name}} || Level: {{player.level}}
              </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_player' item.id player.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn">Add</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h5>{{item.name}} is owned by all players</h5>
        {% endif %}
      </div>
    </div>
<script>
    const dateEl = document.getElementById('id_date');
    // M is Materialize's global variable
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
    const selectEl = document.getElementById('id_trade');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/items/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Item List</h1>

{% for item in items %}
  <div class="card">
    <a href="{% url 'item' item.id %}"
    <div class="card-content">
      <span class="card-title">{{ item.name }}</span>
      <p>Quality: {{ item.quality }}</p>
      <p>Amount: {{ item.amount }}</p>
      {% if item.effect == 'None' %}
        <p>No Effect</p>
      {% else %}
        <p>Effect: {{ item.effect}}</p>
      {% endif %}
    </div>
</a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Item</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'item' item.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- New if/else block -->
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Item</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}